apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: storage1wordpress.file.core.windows.net
    path: /default
  mountOptions:
    - vers=4.1
  persistentVolumeReclaimPolicy: Retain
  storageClassName: azurefile
